# configuration for https://travis-ci.com/cpesch/RouteConverter
sudo: false
language: java
cache:
 directories:
   - $HOME/.m2
jdk:
  - openjdk8
git:
  depth: 3
branches:
  only:
    - master
after_success:
 - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  - support@routeconverter.com
